
spring:
  datasource:
    url: jdbc:postgresql://localhost/family
    password: family
    username: family
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  hibernate:
    temp:
      use_jdbc_metadata_defaults: false




